name: Python package

on:
  push:
    tags:
      - 'v*.*.*'   # z.B. v1.2.3 für Releases

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel twine

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: |
          # Beispiel mit pytest, anpassen wenn andere Tests
          if [ -f pytest.ini ] || [ -d tests ]; then
            pip install pytest
            pytest
          fi

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload dist/*

